# Numpy

[NumPy](https://numpy.org/) is the fundamental package for scientific computing with Python.

### Installation:

<div class="alert alert-block alert-warning">
$ pip install numpy
</div>

or

<div class="alert alert-block alert-warning">
$ conda install numpy
</div>

In [1]:
! pip install numpy

In [1]:
import numpy as np

In [2]:
N = 1000000
my_arr = np.arange(N)
my_list = [i for i in range(N)]

In [3]:
%time for _ in range(10): my_arr2 = 2*my_arr

CPU times: user 15.9 ms, sys: 11.6 ms, total: 27.5 ms
Wall time: 27.6 ms


In [4]:
%time for _ in range(10): my_list2 = [2*x for x in my_list]

CPU times: user 310 ms, sys: 54.2 ms, total: 365 ms
Wall time: 366 ms


In [5]:
366/27.6

13.26086956521739

## Basics:
___

One of the most commonly used functions of NumPy are *NumPy arrays*: The essential difference between lists and NumPy arrays is functionality and speed. lists give you basic operation, but NumPy adds FFTs, convolutions, fast searching, basic statistics, linear algebra, histograms, etc.

The most important difference for data science is the ability to do **element-wise calculations** with *NumPy* arrays.

`axis 0` always refers to row <br>
`axis 1` always refers to column

+ `np.array([1,2,3])`
+ `np.array([(1,2,3),(4,5,6)])`
+ `np.arange(start,stop,step)`

**Placeholders**:
- `np.linspace(0,2,9)`
- `np.zeros((1,2))`
- `np.ones((1,2))`
- `np.random.random((5,5))`
- `np.empty((2,2))`
- `np.full((3, 3), 7)`

In [11]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [10]:
type(arr_1d)

numpy.ndarray

In [15]:
arr_1d[0], arr_1d[3], arr_1d[-1], arr_1d[-2]

(1, 4, 5, 4)

In [25]:
arr_2d = np.array([[1, 2, 3, 4],
                   [-1, 0, 1, 0]])

In [19]:
arr_2d[0][2], arr_2d[0, 2]

(3, 3)

In [20]:
arr_2d.shape

(2, 4)

In [21]:
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8]],
                   
                   [[-1, -2, -3, -4],
                    [-5, -6, -7, -8]],
                   
                   [[11, 12, 13, 14],
                    [15, 16, 17, 18]]])

In [22]:
arr_3d.shape

(3, 2, 4)

In [26]:
arr_3d[1, 0, 2]

-3

In [29]:
arr_3d[2, :, :]

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [31]:
arr_3d[:, 1, :]

array([[ 5,  6,  7,  8],
       [-5, -6, -7, -8],
       [15, 16, 17, 18]])

In [32]:
arr_3d[:, :, 0]

array([[ 1,  5],
       [-1, -5],
       [11, 15]])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [38]:
np.arange(-0.5, 1.1, 0.1)

array([-5.00000000e-01, -4.00000000e-01, -3.00000000e-01, -2.00000000e-01,
       -1.00000000e-01, -1.11022302e-16,  1.00000000e-01,  2.00000000e-01,
        3.00000000e-01,  4.00000000e-01,  5.00000000e-01,  6.00000000e-01,
        7.00000000e-01,  8.00000000e-01,  9.00000000e-01,  1.00000000e+00])

In [42]:
np.linspace(-0.5, 1, 16)

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6,  0.7,  0.8,  0.9,  1. ])

In [49]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.full((3, 4), -7)

array([[-7, -7, -7, -7],
       [-7, -7, -7, -7],
       [-7, -7, -7, -7]])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.random.random((4, 4))

array([[0.58903572, 0.78590464, 0.37887953, 0.87531792],
       [0.16664414, 0.65922083, 0.67297589, 0.75300768],
       [0.09754899, 0.57957748, 0.3717744 , 0.30291825],
       [0.2485746 , 0.38851757, 0.83948559, 0.90271738]])

In [52]:
np.random.uniform(0, 4, (2, 5))

array([[1.31999014, 2.47239128, 0.99578403, 1.26212999, 3.75389943],
       [0.4924544 , 0.03912071, 1.02008476, 3.1409131 , 2.15497137]])

In [53]:
np.random.normal(0, 1, (3, 3))

array([[-1.60075949,  2.92272174, -0.09821871],
       [-1.42681597,  1.18025689,  0.53999068],
       [-0.71931946, -0.04686306, -0.32423992]])

In [62]:
np.random.randint(0, 20, (34,))

array([ 0, 17, 17, 16,  7, 18, 16,  1, 18, 18, 18,  4, 12,  1,  6,  7,  4,
       16, 14, 15, 14, 16, 13,  3,  2,  6, 17,  9, 12, 17,  7,  6,  9, 12])

In [34]:
# np.int8, np.int16, np.int32, np.int64
# np.float16, np.float32, np.float64, np.float128
# np.uint8, np.uint16, np.uint32, np.uint64

In [69]:
b = np.random.randint(0, 20, (34,), dtype=np.uint8)

In [70]:
b.dtype

dtype('uint8')

## Array:

+ `array.shape`	
+ `len(array)`
+ `array.ndim	`
+ `array.size`	
+ `array.dtype`	
+ `array.astype(type)`	


+ `np.copy(array)`	
+ `other = array.copy()`	
+ `array.sort()`
+ `array.sort(axis=0)`

## Linerar algebra